inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "coverage/**/*"
    - "tmp/**/*"
    - "*.gemspec"

Capybara/RSpec/PredicateMatcher:
  Enabled: false
