require:
  - rubocop-rspec

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "coverage/**/*"
    - "tmp/**/*"
    - "*.gemspec"

Capybara/RSpec/PredicateMatcher:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
